name: Test
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [ 12.x ]
      
    # Running tests
    name: Running Tests on ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Generate coverage report
        run: |
          pip install tabulate
          pip install numpy
          pip install pytest
          pip install pytest-cov
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: |
          npm install 
      - name: Run Test
        run: npm run test
      - name: Upload code coverage to codecov
        uses: codecov/codecov-action@v3